import type Phaser from 'phaser';
import BootScene from './scenes/BootScene';
import TitleScene from './scenes/TitleScene';
import PackScene from './scenes/PackScene';
import RouteScene from './scenes/RouteScene';
import TravelScene from './scenes/TravelScene';
import CityScene from './scenes/CityScene';
import EventScene from './scenes/EventScene';
import EndScene from './scenes/EndScene';
import { CoffeeScene } from './scenes/CoffeeScene';
import { PassportScene } from './scenes/PassportScene';
import { ShareScene } from './share/ShareScene';
import { OtterScene } from './scenes/OtterScene';
import { MINIGAME_SCENES } from './minigames/devHarness';
export const SCENES: (typeof Phaser.Scene)[] = [BootScene, TitleScene, PackScene, RouteScene, TravelScene, CityScene, EventScene, EndScene, CoffeeScene, PassportScene, ShareScene, OtterScene, ...MINIGAME_SCENES] as any;
